# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd0edc4f37007e52623505a27490e5f72cf4393e74af789b507e24d57b25147b9065bb40c7c1b57d062ad306f2f30046dac8fcc028f768001529a82eb0406dba

test:
  secret_key_base: 978bd28466dfe8eea61901bf3a37bc1f36bffa4a3551e1d14a7fb27abb561846c7a7687cee39b0401ce7329d8be8a63239dd522fa660d805976d479adeb51953

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
